### ISSUE TITLE
Don't use unicode()

### ISSUE THREAD

**Issue by mgeier** [pybee/toga-gtk#5]
`toga_gtk/widgets/textinput.py` uses `unicode()`, which is not available in Python 3.

This breaks the second example in the docs: http://toga.readthedocs.org/en/latest/tutorial/tutorial-1.html

For Python 3, I guess it would make sense to use `str()` instead, but I don't know if this breaks anything on the Python 2 side ...

If it's actually meant to be Unicode in both Python 2 and 3, you could do something like this:

```Python
try:
    _unicode = unicode  # doesn't exist in Python 3.x
except NameError:
    _unicode = str
```

**Comment by freakboy3742** [comment]
Thanks for the report. That's definitely an oversight. The adaptor you describe already exists in the [libs/utils module](https://github.com/pybee/toga-gtk/blob/master/toga_gtk/libs/utils.py#L4); I've just neglected to use it here.

**Comment by freakboy3742** [comment]
This has become a moot point in the 0.2.2 release, which is Python3 only.
